name: CI/CD Portfolio
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted  # your Proxmox VM runner

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Enable Docker BuildKit
      - name: Set up Docker BuildKit
        run: |
          export DOCKER_BUILDKIT=1

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t idreesahmed396/devops-portfolio:${GITHUB_SHA} .
          
      # 5. Push Docker image
      - name: Push Docker image
        run: |
          docker push idreesahmed396/devops-portfolio:${GITHUB_SHA}

      # 5a. Set up kubeconfig safely
      - name: Set kubeconfig
        run: |
           mkdir -p ~/.kube
           echo "${{ secrets.K3S_KUBECONFIG }}" > ~/.kube/config

      # 6. Restart deployment
      - name: Update K3s deployment
        run: |
          kubectl --kubeconfig ~/.kube/config -n default set image deployment/portfolio \
          portfolio=idreesahmed396/devops-portfolio:${GITHUB_SHA} --record
          kubectl --kubeconfig ~/.kube/config -n default rollout status deployment/portfolio --timeout=120s